environment:
 VK_SDK_PATH: "C:\\VulkanSDK\\1.0.46.0\\"

image:
 - Visual Studio 2017
 - Visual Studio 2015

clone_depth: 1

install:
 - git submodule update --init --recursive
 - appveyor DownloadFile https://vulkan.lunarg.com/sdk/download/1.0.46.0/windows/VulkanSDK-1.0.46.0-Installer.exe -FileName vulkan.exe
 - vulkan.exe /S

before_build:
 - cd docs
 - call build.bat
 - cd ..

build_script:
 - msbuild Benchmarking-Tool.sln /t:Build /p:Configuration=Release;Platform=x64 /p:Configuration=Release;Platform=x86 /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll
 - msbuild Benchmarking-Tool.sln /t:Installer /p:Configuration=Release;Platform=x86 /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll
 - msbuild Benchmarking-Tool.sln /t:Install-Bundle /p:Configuration=Release;Platform=x86 /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll
 