environment:
 VK_SDK_PATH: "C:\\VulkanSDK\\1.0.46.0\\"

image:
 - Visual Studio 2017
 - Visual Studio 2015

clone_depth: 1

cache:
 - vulkan_1.0.46.0

install:
 - git submodule update --init --recursive
 - ps: if(!(Test-Path vulkan_1.0.46.0)) {mkdir vulkan_1.0.46.0}
 - ps: if(!(Test-Path vulkan_1.0.46.0/vulkan.exe)) { Invoke-WebRequest -Uri https://vulkan.lunarg.com/sdk/download/1.0.46.0/windows/VulkanSDK-1.0.46.0-Installer.exe?Human=true -OutFile vulkan_1.0.46.0/vulkan.exe }
 - ps: ./vulkan_1.0.46.0/vulkan.exe /S

notifications:
 - provider: Slack
   incoming_webhook:
     secure: reZgP+MAKCYu9pDcH573P1Ecs9AZxzb+VqQVXNl10D/2RHG+SlxWI5LGN8HYP2AwoU+mfPb8TU0I8ZXaOvGKGu6ulW91E+qvPwlhZm3vIeI= 


before_build:
 - cd docs
 - call build.bat
 - cd ..

build_script:
 - msbuild Benchmarking-Tool.sln /t:Build /p:Configuration=Release;Platform=x64 /p:Configuration=Release;Platform=x86 /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll
 - msbuild Benchmarking-Tool.sln /t:Installer /p:Configuration=Release;Platform=x86 /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll
 - msbuild Benchmarking-Tool.sln /t:Install-Bundle /p:Configuration=Release;Platform=x86 /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll
 