image:
 - Visual Studio 2017
 - Visual Studio 2015

clone_depth: 1

before_build:
 - cd docs
 - call build.bat
 - cd ..

build: 
 verbosity: minimal
 msbuild Benchmarking-Tool.sln /t:Build /p:Configuration=Release;Platform=x64 /p:Configuration=Release;Platform=x86 /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll
 msbuild Benchmarking-Tool.sln /t:Installer /p:Configuration=Release;Platform=x86 /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll
 msbuild Benchmarking-Tool.sln /t:Install-Bundle /p:Configuration=Release;Platform=x86 /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll
 