environment:
 VK_SDK_PATH: "C:\\VulkanSDK\\1.1.82.1\\"

version: '1.2.0.{build}'

assembly_info:
  patch: true
  file: Frontend\Properties\AssemblyInfo.cs
  assembly_version: "{version}"
  assembly_file_version: "{version}"

image:
 - Visual Studio 2017

clone_depth: 1

before_build:
 - nuget restore

install:
 # Download Vulkan SDK
 - ps: Invoke-WebRequest -Uri https://sdk.lunarg.com/sdk/download/1.1.82.1/windows/VulkanSDK-1.1.82.1-Installer.exe?Human=true -OutFile vulkan.exe
 - ps: .\vulkan.exe /S
 # Download Visual Studio redistributables
 - ps: if(!(Test-Path .\OCAT-Installer\redist)) { mkdir .\OCAT-Installer\redist }
 - ps: Invoke-WebRequest -Uri https://download.microsoft.com/download/5/7/b/57b2947c-7221-4f33-b35e-2fc78cb10df4/vc_redist.x64.exe -OutFile .\OCAT-Installer\redist\vc_redist.x64.exe
 - ps: Invoke-WebRequest -Uri https://download.microsoft.com/download/1/d/8/1d8137db-b5bb-4925-8c5d-927424a2e4de/vc_redist.x86.exe -OutFile .\OCAT-Installer\redist\vc_redist.x86.exe
 
notifications:
 - provider: Slack
   incoming_webhook:
     secure: reZgP+MAKCYu9pDcH573P1Ecs9AZxzb+VqQVXNl10D/2RHG+SlxWI5LGN8HYP2AwoU+mfPb8TU0I8ZXaOvGKGu6ulW91E+qvPwlhZm3vIeI= 

build_script:
 - ps: $Env:PLATFORM_TOOLSET="v141"
 - msbuild OCAT.sln /t:Build /p:Configuration=Release;Platform=x64 /p:PlatformToolset=%PLATFORM_TOOLSET% /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll
 - msbuild OCAT.sln /t:Build /p:Configuration=Release;Platform=x86 /p:PlatformToolset=%PLATFORM_TOOLSET% /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll
 - msbuild OCAT.sln /t:Installer /p:Configuration=Release;Platform=x64 /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll
 - msbuild OCAT.sln /t:Install-Bundle /p:Configuration=Release;Platform=x64 /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll
 
after_build:
 - ps: copy .\OCAT-Installer\bin\x64\Release\OCAT.exe "OCAT_$($Env:APPVEYOR_BUILD_VERSION).exe"
 - ps: Push-AppveyorArtifact "OCAT_$($Env:APPVEYOR_BUILD_VERSION).exe"
